spring:
  application:
    name: user_with_audit
  datasource:
    url: jdbc:h2:mem:dbuser
    driverClassName: org.h2.Driver
    username: root
    password: root
  properties:
    org.hibernate.envers.audit_table_suffix: _HIST
    org.hibernate.envers.revision_field_name: REVISION_ID
    org.hibernate.envers.revision_type_field_name: REVISION_TYPE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        dialect: org.hibernate.dialect.H2Dialect
